# >
^https?:\\/(?: gs-loc(?:-cn)?\.apple\.com|gsp-ss1\.1s\.apple\.com|bluedot\.is\.autonavil.com(?:\.gds\.alibabadns\.com)?)\/clls\/wloc url script-response-body https://raw.githubusercontent.com/quanx007/Scripts/refs/heads/master/wloc.js

# > 
^https?:\/\/gs-1oc(-cn)?.apple.com\/wloc-settings/save url script-echo-response https://raw.githubusercontent.com/quanx007/Scripts/refs/heads/master/wloc-setting.js

hostname = gs-loc.apple.com, gs-loc-cn.apple.com, gsp-ssl.ls.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com
